### ISSUE TITLE
Unable to get Calendar to render in React 15.1.0

### ISSUE THREAD

**Issue by aaronmagi** [zippyui/react-date-picker#98]
Hi,

I am trying to get the most basic Calendar to render in React 15.1.0.  I can not get even the basic Calendar to render.  

Error in console:

      warning.js:44 Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `CalendarTest`.warning @ warning.js:44createElement @ ReactElementValidator.js:221render @ CalendarTest.js:19_renderValidatedComponentWithoutOwnerOrContext @ ReactCompositeComponent.js:815_renderValidatedComponent @ ReactCompositeComponent.js:841performInitialMount @ ReactCompositeComponent.js:351mountComponent @ ReactCompositeComponent.js:244mountComponent @ ReactReconciler.js:46mountChildren @ ReactMultiChild.js:215_createInitialChildren @ ReactDOMComponent.js:649mountComponent @ ReactDOMComponent.js:489mountComponent @ ReactReconciler.js:46mountChildren @ ReactMultiChild.js:215_createInitialChildren @ ReactDOMComponent.js:649mountComponent @ ReactDOMComponent.js:489mountComponent @ ReactReconciler.js:46_mountChildAtIndex @ ReactMultiChild.js:400_updateChildren @ ReactMultiChild.js:316updateChildren @ ReactMultiChild.js:276_updateDOMChildren @ ReactDOMComponent.js:883updateComponent @ ReactDOMComponent.js:712receiveComponent @ ReactDOMComponent.js:668receiveComponent @ ReactReconciler.js:127updateChildren @ ReactChildReconciler.js:85_reconcilerUpdateChildren @ ReactMultiChild.js:189_updateChildren @ ReactMultiChild.js:288updateChildren @ ReactMultiChild.js:276_updateDOMChildren @ ReactDOMComponent.js:883updateComponent @ ReactDOMComponent.js:712receiveComponent @ ReactDOMComponent.js:668receiveComponent @ ReactReconciler.js:127_updateRenderedComponent @ ReactCompositeComponent.js:775_performComponentUpdate @ ReactCompositeComponent.js:753updateComponent @ ReactCompositeComponent.js:672performUpdateIfNecessary @ ReactCompositeComponent.js:585performUpdateIfNecessary @ ReactReconciler.js:160runBatchedUpdates @ ReactUpdates.js:151perform @ Transaction.js:136perform @ Transaction.js:136perform @ ReactUpdates.js:90flushBatchedUpdates @ ReactUpdates.js:177closeAll @ Transaction.js:202perform @ Transaction.js:149batchedUpdates @ ReactDefaultBatchingStrategy.js:63enqueueUpdate @ ReactUpdates.js:209enqueueUpdate @ ReactUpdateQueue.js:22enqueueSetState @ ReactUpdateQueue.js:201ReactComponent.setState @ ReactComponent.js:67(anonymous function) @ app.js:348tryCatchReject @ makePromise.js:845runContinuation1 @ makePromise.js:804Fulfilled.when @ makePromise.js:592Pending.run @ makePromise.js:483Scheduler._drain @ Scheduler.js:62Scheduler.drain @ Scheduler.js:27run @ env.js:63
      unhandledRejection.js:23 Potentially unhandled rejection [1] Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `CalendarTest`.
          at invariant (http://localhost:8081/built/bundle.js:1531:16)
          at ReactCompositeComponentWrapper.instantiateReactComponent [as _instantiateReactComponent] (http://localhost:8081/built/bundle.js:15060:135)
          at ReactCompositeComponentWrapper.performInitialMount (http://localhost:8081/built/bundle.js:15480:37)
          at ReactCompositeComponentWrapper.mountComponent (http://localhost:8081/built/bundle.js:15369:22)
          at Object.mountComponent (http://localhost:8081/built/bundle.js:8475:36)
          at ReactDOMComponent.mountChildren (http://localhost:8081/built/bundle.js:14573:45)
          at ReactDOMComponent._createInitialChildren (http://localhost:8081/built/bundle.js:11551:33)
          at ReactDOMComponent.mountComponent (http://localhost:8081/built/bundle.js:11391:13)
          at Object.mountComponent (http://localhost:8081/built/bundle.js:8475:36)
          at ReactDOMComponent.mountChildren (http://localhost:8081/built/bundle.js:14573:45)

CalendarPage.js

    'use strict';

    const React = require('react');
    const ReactDOM = require('react-dom');

    const Calendar = require('react-date-picker');
    //const TransitionView = require('react-date-picker');

    class CalendarTest extends React.Component {

      constructor(props) {
        super(props);
      }
      render() {

        return (

            <Calendar />
        );
      }
    }

    module.exports = CalendarTest

app.js 

const CalendarTest = require('./CalendarTest');

      render()

       ....
       <CalendarPage />

package.json 

      "dependencies": {
        "babel-core": "^6.8.0",
        "babel-loader": "^6.2.4",
        "babel-preset-es2015": "^6.6.0",
        "babel-preset-react": "^6.5.0",
        "babel-preset-stage-2": "^6.5.0",
        "react": "^15.1.0",
        "react-dom": "^15.1.0",
        "rest": "^1.3.2",
        "sockjs-client": "^1.0.3",
        "stompjs": "^2.3.3",
        "webpack": "^1.13.0",
        "when": "^3.7.7",
        "react-bootstrap": "^0.29.4",
        "jquery":  "^2.2.3",
        "react-ux-password-field":  "^0.9.12",
        "react-dropzone":  "^3.5.0",
        "superagent":  "^2.0.0",
        "moment":  "^2.13.0",
        "moment-timezone":  "^0.5.4",
        "json-loader":  "^0.5.4",
        "react-date-picker":  "^5.3.12"

**Comment by radubrehar** [comment]
You should use 
```jsx
import { Calendar } from 'react-date-picker'

//or, using require:
const Calender = require('react-date-picker').Calendar
```

**Comment by aaronmagi** [comment]
@radubrehar       

Thanks 


import { Calendar } from 'react-date-picker'   (works)

//or, using require:
const Calender = require('react-date-picker').Calendar  (didnt work)

**Comment by aaronmagi** [comment]
@radubrehar 

One other question for you,

         <TransitionView>
          <Calendar
            dateFormat="DD/MM/YYYY HH:mm:ss"
            onChange={(dateString, { dateMoment, timestamp}) => {
              console.log("dateString", dateString);;
            }}
          />
        </TransitionView>

This will keep rendering the correct date but the HH:mm:ss is always 00:00:00 on change.

**Comment by dev-zippyui** [comment]
@aaronmagi is this still valid with the latest version on npm? Thanks!
